config:
  target: "https://staging.example.com"
  payload:
      path: "config.csv"
      fields:
        - "duration"
        - "arrivalRate"
        - "weightRead"
        - "weightwrite" 
  phases:
    - duration: duration
    - arrivalRate: arrivalRate
