FROM artilleryio/artillery

WORKDIR .

COPY valores.csv valores.csv
COPY start_0.yml start_0.yml
#COPY start_1.yml start_1.yml
#COPY start_2.yml start_2.yml
#COPY start_3.yml start_3.yml
COPY workload_0.yml workload_0.yml
#COPY workload_1.yml workload_1.yml
#COPY workload_2.yml workload_2.yml
#COPY workload_3.yml workload_3.yml
#COPY mine.yml mine.yml