FROM artilleryio/artillery

WORKDIR .

COPY users.csv users.csv
COPY weights.csv weights.csv
COPY start.yml start.yml
COPY workload_0.yml workload_0.yml
COPY workload_1.yml workload_1.yml
COPY workload_2.yml workload_2.yml
COPY workload_3.yml workload_3.yml
