services:

  client_0:
    image: client
    ports: 
      - "8080:8080"
    networks:
      net:
        ip: 172.19.0.2
    command: java -Djavax.net.ssl.trustStore=security/clientcacerts.jks -Djavax.net.ssl.trustStorePassword=password -cp client.jar client.Server "https://172.19.10.0:8080" 0
  
  client_1:
    image: client
    ports: 
      - "8081:8080"
    networks:
      net:
        ip: 172.19.0.3
    command: java -Djavax.net.ssl.trustStore=security/clientcacerts.jks -Djavax.net.ssl.trustStorePassword=password -cp client.jar client.Server "https://172.19.10.1:8080" 0

  client_2:
    image: client
    ports: 
      - "8082:8080"
    networks:
      net:
        ip: 172.19.0.4
    command: java -Djavax.net.ssl.trustStore=security/clientcacerts.jks -Djavax.net.ssl.trustStorePassword=password -cp client.jar client.Server "https://172.19.10.2:8080" 0

  client_3:
    image: client
    ports: 
      - "8083:8080"
    networks:
      net:
        ip: 172.19.0.5
    command: java -Djavax.net.ssl.trustStore=security/clientcacerts.jks -Djavax.net.ssl.trustStorePassword=password -cp client.jar client.Server "https://172.19.10.3:8080" 0

  proxy_0:
    image: proxy
    networks:
      net:
        ip: 172.19.10.0
    command: java -Djavax.net.ssl.keyStore=security/serverkeystore.jks -Djavax.net.ssl.keyStorePassword=password -cp server.jar proxy.Server 10 0 4
  
  proxy_1:
    image: proxy
    networks:
      net:
        ip: 172.19.10.1
    command: java -Djavax.net.ssl.keyStore=security/serverkeystore.jks -Djavax.net.ssl.keyStorePassword=password -cp server.jar proxy.Server 11 0 4

  proxy_2:
    image: proxy
    networks:
      net:
        ip: 172.19.10.2
    command: java -Djavax.net.ssl.keyStore=security/serverkeystore.jks -Djavax.net.ssl.keyStorePassword=password -cp server.jar proxy.Server 12 0 4
  
  proxy_3:
    image: proxy
    networks:
      net:
        ip: 172.19.10.3
    command: java -Djavax.net.ssl.keyStore=security/serverkeystore.jks -Djavax.net.ssl.keyStorePassword=password -cp server.jar proxy.Server 13 0 4
  
  replica_0:
    image: replica
    networks:
      net:
        ip: 172.19.20.0
    command: java -Djavax.net.ssl.keyStore=security/serverkeystore.jks -Djavax.net.ssl.keyStorePassword=password -cp server.jar proxy.Server 14 0 4
  
  replica_1:
    image: replica
    networks:
      net:
        ip: 172.19.20.1
  
  replica_2:
    image: replica
    networks:
      net:
        ip: 172.19.20.2

  replica_3:
    image: replica
    networks:
      net:
        ip: 172.19.20.3

  redis_0:
    image: redis
    networks:
      net:
        ip: 172.19.30.0
  
  redis_1:
    image: redis
    networks:
      net:
        ip: 172.19.30.1
  
  redis_2:
    image: redis
    networks:
      net:
        ip: 172.19.30.2

  redis_3:
    image: redis
    networks:
      net:
        ip: 172.19.30.3

networks:
  net:
    driver: bridge
    subnet: 172.19.0.0/16