public enum LedgerRequestType {
    HOME,
    CREATE_ACCOUNT,
    GET_EXTRACT,
    SEND_TRANSACTION,
    GET_TOTAL_VALUE,
    GET_GLOBAL_VALUE,
    GET_LEDGER,
    LOAD_MONEY,
    GET_BALANCE,
    GET_TRANSACTIONS_TO_MINERATE,
    MINE_BLOCK,
    GET_LAST_MINED_BLOCK;
}


